CREATE OR REPLACE PROCEDURE "OPS_APP"."INELIGIBLE_INTRUMENTS" (

P_CASE_ID  NUMBER,
P_CLIENT_NAME  VARCHAR2

)
AS
begin

update Prefiling.Case_Transaction
set exclude_reason = 'INELIGIBLE INTRUMENT (SWAP/CFD) - '|| sysdate
WHERE (CASE_ID IN (P_CASE_ID))
AND CLIENT_ID IN (SELECT CLIENT_ID FROM FRT.CLIENT WHERE SHORT_NAME IN(P_CLIENT_NAME))
AND ACCOUNT_ID IN (SELECT ACCOUNT_ID FROM ACCOUNT WHERE STATUS IN ('ACTIVE','APPROVAL'))
AND EXCLUDE_REASON IS NULL
AND (INSTRUMENT_NAME LIKE '%SWP%' OR INSTRUMENT_NAME LIKE '%SWAP%' OR INSTRUMENT_NAME LIKE '%CFD%'
OR TRANS_TYPE LIKE '%SWP%' OR TRANS_TYPE LIKE '%SWAP%' OR TRANS_TYPE LIKE '%CFD%'
OR INSTRUMENT_CODE LIKE '%SWP%' OR INSTRUMENT_CODE LIKE '%SWAP%' OR INSTRUMENT_CODE LIKE '%CFD%' 
OR symbol LIKE '%SWP%' OR symbol LIKE '%SWAP%' OR symbol LIKE '%CFD%'
OR INSTRUMENT_NAME LIKE '%SWP%' OR INSTRUMENT_NAME LIKE '%SWAP%' OR INSTRUMENT_NAME LIKE '%CFD%'
OR TRANS_TYPE LIKE '%SWP%' OR TRANS_TYPE LIKE '%SWAP%' OR TRANS_TYPE LIKE '%CFD%'
OR INSTRUMENT_CODE LIKE '%SWP%' OR INSTRUMENT_CODE LIKE '%SWAP%' OR INSTRUMENT_CODE LIKE '%CFD%'
OR symbol LIKE '%SWP%' OR symbol LIKE '%SWAP%' OR symbol LIKE '%CFD%')
;
END ;





